apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "patient-api-chart.fullname" . }}
  labels:
    app: patient-api
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: patient-api
  template:
    metadata:
      labels:
        app: patient-api
    spec:
      containers:
        - name: patient-api
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
