apiVersion: v1
kind: Service
metadata:
  name: {{ include "patient-api-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: patient-api
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
