apiVersion: v1
kind: Service
metadata:
  name: patient-api-service
  namespace: devops-project
spec:
  selector:
    app: patient-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080
  type: NodePort
