apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portal-ui-chart.fullname" . }}
  labels:
    app: portal-ui
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: portal-ui
  template:
    metadata:
      labels:
        app: portal-ui
    spec:
      containers:
        - name: portal-ui
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
