apiVersion: v1
kind: Service
metadata:
  name: {{ include "portal-ui-chart.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: portal-ui
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.containerPort }}
