apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-ui
  namespace: healthcare
  labels:
    app: portal-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-ui
  template:
    metadata:
      labels:
        app: portal-ui
    spec:
      containers:
        - name: portal-ui
          image: portal-ui:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80
