apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-ui
  labels:
    app: portal-ui
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portal-ui
  template:
    metadata:
      labels:
        app: portal-ui
    spec:
      containers:
        - name: portal-ui
          image: sudheerthota/portal-ui:latest
          ports:
            - containerPort: 8080
