apiVersion: v1
kind: Service
metadata:
  name: portal-ui
  namespace: healthcare
spec:
  type: NodePort
  selector:
    app: portal-ui
  ports:
    - port: 80
      targetPort: 80
      nodePort: 32080
