name: Build and Push Images

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Patient API Image
        run: |
          docker build -t sudheerthota/patient-api:latest ./services/patient-api
          docker push sudheerthota/patient-api:latest

      - name: Build and Push Appointment Service Image
        run: |
          docker build -t sudheerthota/appointment-service:latest ./services/appointment-service
          docker push sudheerthota/appointment-service:latest

      - name: Build and Push Billing Service Image
        run: |
          docker build -t sudheerthota/billing-service:latest ./services/billing-service
          docker push sudheerthota/billing-service:latest

      - name: Build and Push Portal UI Image
        run: |
          docker build -t sudheerthota/portal-ui:latest ./services/portal-ui
          docker push sudheerthota/portal-ui:latest
